name: Ejecutar arbitraje.py

on:
  workflow_dispatch:  # Permite ejecutar manualmente desde GitHub

jobs:
  run-arbitraje:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias (si tienes requirements.txt)
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Exportar variables de entorno
        run: |
          echo "USER=${{ secrets.USER }}" >> $GITHUB_ENV
          echo "CHAT_ID=${{ secrets.CHAT_ID }}" >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV
          echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> $GITHUB_ENV
          echo "TICKERS=${{ secrets.TICKERS }}" >> $GITHUB_ENV


      - name: Ejecutar arbitraje.py
        run: python arbitraje.py
