name: Ejecutar arbitraje.py

on:
  workflow_dispatch:  # Permite ejecutar manualmente desde GitHub

jobs:
  run-arbitraje:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias (si tienes requirements.txt)
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ejecutar arbitraje.py
        run: python arbitraje.py
